---
- name: Deploy Galaxy Unit
  template:
    owner: root
    group: root
    mode: 0644
    src: galaxy.service.j2
    dest: /etc/systemd/system/galaxy.service
  notify:
    - daemon reload
    - galaxy mule start

- name: Enable Galaxy Unit
  systemd:
    name: galaxy.service
    enabled: yes
